[workspace]
members = [
  "main",
  "parser",
  "sourcemap",
  "syntax",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
thiserror = "1.0.63"
bumpalo = "3.16.0"
serde = { version = "1.0.209", features = ["derive"] }
toml = "0.8.19"
clap = { version = "4.5.16", features = ["derive"] }
sourcemap = { path = "./sourcemap" }
syntax = { path = "./syntax" }
parser = { path = "./parser" }
