[workspace]
members = [
  "main",
  "parser",
  "sourcemap",
  "syntax",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
thiserror = "1.0.48"
bumpalo = "3.14.0"
sourcemap = { path = "./sourcemap" }
syntax = { path = "./syntax" }
parser = { path = "./parser" }
