[package]
name = "runtime"
version.workspace = true
edition.workspace = true

[dependencies]
wasi-common.workspace = true
wasmtime.workspace = true

clap.workspace = true

[features]
default = ["minrt-runtime"]
minrt-runtime = []
