[package]
name = "parser"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plex = "0.2.5"
peg = "0.8.1"
thiserror.workspace = true
syntax.workspace = true
sourcemap.workspace = true
