[package]
name = "data_structure"
version.workspace = true
edition.workspace = true

[features]

[dependencies]
bitvec.workspace = true
typed-arena.workspace = true
rustc-hash.workspace = true
indexmap.workspace = true

cfg-if.workspace = true
