[package]
name = "ir_asm_virtual"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_structure.workspace = true

ir_closure.workspace = true
